name: ddm_pj_flutter_dp
description: A simple personal finance Flutter app with login, register and control screens.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^7.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
